GE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('swenergy.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

swenergy/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from django.views.generic import TemplateView

from swenergy.utils import GeraPDFMixin
from . import views

app_name = 'swenergy'

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('data/', views.IndexViewJSON.as_view(), name='index_json'),
    path('api/data/sensor/<int:pk>/', views.GetSensorDataAPI.as_view(), name='get_sensor_data'),
    path('api/data/fase/<int:pk>/', views.GetFaseDataAPI.as_view(), name='get_sensor_data'),
    path('api/data/', views.GetDataAPI.as_view(), name='get_data'),

    path('detalhes/<int:pk>/', views.detalhes.as_view(), name='detalhes'),
    path('addSensor/<int:pk>/', views.addSensor.as_view(), name='addSensor'),
    path('editar/<int:pk>/', views.editar.as_view(), name='editar'),
    path('cadastro/', views.cadastro.as_view(), name='cadastro'),
    path('login/', auth_views.LoginView.as_view(template_name='swenergy/login.html'), name = 'login'),

    path('indexPredio/<int:pk>/', views.indexPredio.as_view(), name='indexPredio'),
    path('addPredio/', views.addPredio.as_view(), name='addPredio'),
    path('editarPredio/<int:pk>/', views.editarPredio.as_view(), name='editarPredio'),
    path('detalhesPredio/<int:pk>/', views.detalhesPredio.as_view(), name='detalhesPredio'),

    path('niveis/<int:pk>/', views.NiveisEnergia.as_view(), name='niveis'),
    path('eficiencia/<int:pk>/', views.Eficiencia.as_view(), name='eficiencia'),
    path('contas/<int:pk>/', views.Contas.as_view(), name='contas'),
    #testePDF
    path('relatorio/', views.GeraPDF, name='relatorio'),
    #SerializadorPDF
    path('relatoriopdf/<int:pk>/', views.RelatorioPDF.as_view(), name='relatoriopdf'),
    #Baixar relatorio
    path('getRelatorio/', views.get_relatorio, name='getRelatorio'),

    #alertas
    path('enviarAlerta/', views.EnviarAlerta.as_view(), name='alerta'),
    path('api/sensor/', views.Controller.as_view(), name='controller')
]

swenergy/models.py
from django.db import models

from django.utils import timezone
import datetime
from django.contrib.auth.models import User
# Create your models here.
class Predio(models.Model):
    nome = models.CharField(max_length=50)
    Co2 = models.FloatField(null=True) # ambienteal
    KWh = models.FloatField(null=True) #KWh por mes
    economico = models.FloatField(null=True)
    meta = models.FloatField(null=True)

    area = models.FloatField(null=True)
    populacao = models.FloatField(null=True)
    pavimentos = models.FloatField(null=True)
    PotInst = models.FloatField(null=True)
    geracaoFV = models.BooleanField(default=False)
    idade = models.IntegerField(null=True)

    Iluminacao = models.CharField(max_length=1, null=True)
    CondAr = models.CharField(max_length=1, null=True)
    envoltoria = models.CharField(max_length=1, null=True)

    tarifaNP = models.FloatField(null=True)
    tarifaFP = models.FloatField(null=True)

    def __str__(self):
        return self.nome


class Sensor(models.Model):
    titulo  = models.CharField(max_length=50)
    time    = models.TimeField(null=True)        # h m s
    pt      = models.FloatField(null=True)       # Potência ativa total
    qt      = models.FloatField(null=True)       # Potência reativa total
    st      = models.FloatField(null=True)       # Potência aparente total 
    itrms   = models.FloatField(null=True)       # Corrente total
    pft     = models.FloatField(null=True)       # Fator de potência total
    freq    = models.FloatField(null=True)       # Frequência
    ept     = models.FloatField(null=True)       # Consumo de energia ativa total
    eqt     = models.FloatField(null=True)       # Consumo de energia reativa total      
    yuaub   = models.FloatField(null=True)       # Ângulo entre Tensão Fase A e Fase B
    yuauc   = models.FloatField(null=True)       # Ângulo entre Tensão Fase B e Fase C
    yubuc   = models.FloatField(null=True)       # Ângulo entre Tensão Fase B e Fase C
    tpsd    = models.FloatField(null=True)       # Temperatura
    predio = models.ForeignKey(Predio, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.titulo
    class Meta:
        verbose_name_plural = 'Sensores'

class Fase(models.Model):
    #tipo    = ('A'),('B'),('C')
    tipo    = models.CharField(max_length=2, null=True)
    p       = models.FloatField(null=True)       # Potência ativa
    q       = models.FloatField(null=True)       # Potência reativa
    s       = models.FloatField(null=True)       # Potência aparente
    urms    = models.FloatField(null=True)       # Tensão
    itrms   = models.FloatField(null=True)       # Corrente
    pf      = models.FloatField(null=True)       # Fator de potência 
    pg      = models.FloatField(null=True)       # Ângulo entre a tensão e corrente
    ep      = models.FloatField(null=True)       # Consumo de energia ativa
    eq      = models.FloatField(null=True)       # Consumo de energia reativa
    sensor  = models.ForeignKey(Sensor, on_delete = models.CASCADE, null=True) 
    def __str__(self):
        return self.tipo

class Consumo(models.Model):
    data = models.DateField()
    tipo    = models.CharField(max_length=6,default='diario')
    inicio = models.FloatField(null=True)
    fim = models.FloatField(null=True)
    total = models.FloatField(null=True)
    media = models.FloatField(null=True)
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return ('Sensor: {0} | Consumo: {1} | Data: {2}').format(self.sensor, self.total, self.data)

class Custo(models.Model):
    #Consumo mensal está relacionado à um custo
    consumo = models.OneToOneField(Consumo, on_delete=models.CASCADE, null=True)
    tarifaNP = models.FloatField(null=True)
    tarifaFP = models.FloatField(null=True)
    NP = models.FloatField(null=True)
    FP = models.FloatField(null=True)
    def __str__(self):
        return ('Consumo do Mês {}'.format(self.consumo.data))

class Eficiencia(models.Model):
    #Nível de eficiencia
    data = models.DateField()
    Iluminação = models.CharField(max_length=1)
    CondAr = models.CharField(max_length=1)
    envoltoria = models.CharField(max_length=1)
    predio = models.ForeignKey(Predio, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return('Eficiência do edifício {}').format(self.predio)

swenergy/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Sensor, Fase, Consumo, Predio, Custo
from .utils import GeraPDFMixin, Email
from django.db import models
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from reportlab.pdfgen import canvas

from django.http import HttpResponse, HttpRequest, JsonResponse
from django.http.request import QueryDict
import json, datetime
from calendar import monthrange
from django.template.loader import get_template
from io import BytesIO
#import wget

from django.http import StreamingHttpResponse
from django.views.decorators.csrf import csrf_exempt

#Create your views here.
@method_decorator(
   login_required(login_url='/login'), name='dispatch'
)
class index(View):
    def get(self,request,*args,**kwargs):
        predios = Predio.objects.all()       
        contexto = {'predios':predios}

        return render(request,'swenergy/index.html', contexto)
    @csrf_exempt
    def post(self,request,*args,**kwargs):
        contexto = {'data':request.POST, 'msg':'Metodo POST'}
        sensor = Sensor()
        pt      = request.POST['pt']
        qt      = request.POST['qt']
        st      = request.POST['st']
        itrms   = request.POST['itrms']
        pft     = request.POST['pft']
        freq    = request.POST['freq']
        ept     = request.POST['ept']
        eqt     = request.POST['eqt']
        yuaub   = request.POST['yuaub']
        yuauc   = request.POST['yuauc']
        yubuc   = request.POST['yubuc']
        tpsd    = request.POST['tpsd']
        return render(request,'swenergy/index.html',contexto)
@method_decorator(
    login_required(login_url='/login'), name='dispatch'
)
class indexPredio(View):
    #@csrf_exempt
    def get(self,request,*args,**kwargs):
        predio = get_object_or_404(Predio, pk=kwargs['pk'])
        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area

        mes = datetime.date.today().month
        ano = datetime.date.today().year
        consumos_diarios = Consumo.objects.filter(tipo='diario').filter(sensor=sensor).filter(data__month=mes).order_by('data')
        consumos_mensais = Consumo.objects.filter(tipo='mensal').filter(sensor=sensor).filter(data__month=mes).order_by('data')
        filtro = request.GET.get('filtro')
        if filtro:
            print(filtro)
            consumos_mensais =  consumos_mensais.filter(data__month=filtro).filter(data__year=ano).order_by('data')
            consumos_diarios = consumos_diarios.filter(data__month=filtro).filter(data__year=ano).order_by('data')
        contexto = {
            'predio':predio,
            'consumos_diarios':consumos_diarios,
            'consumos_mensais':consumos_mensais, 
            'consumo_mes':consumo_mes, 
            'consumo_pessoa':consumo_pessoa, 
            'consumo_area':consumo_area
            }
        return render(request,'swenergy/indexPredio.html', contexto)

    def post(self,request,*args,**kwargs):
        pass

@method_decorator(
    login_required(login_url='/login'), name='dispatch'
)
class detalhes(View):
    def get(self, request, *args, **kwargs):
        sensor = get_object_or_404(Sensor, pk=kwargs['pk'])
        predio = sensor.predio

        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area

        consumos_diarios = Consumo.objects.filter(tipo='diario').filter(sensor=sensor)
        consumos_mensais = Consumo.objects.filter(tipo='mensal').filter(sensor=sensor)
        contexto = {
            'sensor':sensor,
            'predio':predio,
            'consumos_diarios':consumos_diarios,
            'consumos_mensais':consumos_mensais,
            'consumo_mes':consumo_mes, 
            'consumo_pessoa':consumo_pessoa, 
            'consumo_area':consumo_area
        }
        return render(request, 'swenergy/detalhes.html', contexto)

@method_decorator(
    login_required(login_url='/login'), name='dispatch'
)
class detalhesPredio(View):
    def get(self, request, *args, **kwargs):
        predio = get_object_or_404(Predio, pk=kwargs['pk'])

        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area

        contexto = {
            'predio':predio, 
            'consumo_mes':consumo_mes, 
            'consumo_pessoa':consumo_pessoa, 
            'consumo_area':consumo_area
            }

        return render(request, 'swenergy/detalhesPredio.html', contexto)

@method_decorator(
    login_required(login_url='/login'), name='dispatch'
)
class addSensor(View):
    def get(self, request, *args, **kwargs):
        predio = get_object_or_404(Predio, pk=kwargs['pk'])
        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area

        contexto = {
            'predio':predio, 
            'consumo_mes':consumo_mes, 
            'consumo_pessoa':consumo_pessoa, 
            'consumo_area':consumo_area
            }
        return render(request, 'swenergy/formSensor.html', contexto)
    
    def post(self, request, *args, **kwargs):
        predio = get_object_or_404(Predio, pk=kwargs['pk'])
        sensor  = Sensor(titulo=request.POST['titulo'], predio=predio)
        sensor.save()
        fa      = Fase(tipo='A', sensor = sensor)
        fb      = Fase(tipo='B', sensor = sensor)
        fc      = Fase(tipo='C', sensor = sensor)
        fa.save()
        fb.save()
        fc.save()

        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area
        contexto = {
            'sensor':sensor,
            'predio':predio, 
            'consumo_mes':consumo_mes, 
            'consumo_pessoa':consumo_pessoa, 
            'consumo_area':consumo_area,
            'msg':'Sensor cadastrado!'
            }
        return render(request, 'swenergy/detalhes.html',contexto)
@method_decorator(
    login_required(login_url='/login'), name='dispatch'
)
class addPredio(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'swenergy/formPredio.html')
    
    def post(self, request, *args, **kwargs):
        predio  = Predio(
            nome        = request.POST['titulo'],
            KWh         = request.POST['kwh'],
            economico   = request.POST['economico'],
            meta        = request.POST['meta'],
            area        = request.POST['area'], 
            populacao   = request.POST['pop'], 
            pavimentos  = request.POST['pav'], 
            PotInst     = request.POST['pi'], 
            tarifaFP    = request.POST['tarifaFP'],
            idade       = request.POST['idade'] 
            )
        geracaofv = request.POST.getlist('GFV')
        for gfv in geracaofv:
            if gfv=='1':
                predio.geracaoFV=True

            elif gfv=='2':

                predio.geracaoFV=False
            else:
                msg_erro = 'Dados inválidos!'
        predio.save()
        contexto = {'predio':predio, 'msg':'Edifício cadastrado!'}
        return render(request, 'swenergy/detalhesPredio.html',contexto)

@method_decorator(
    login_required(login_url='/login'), name='dispatch'
)
class editar(View):
    def get(self,request,*args,**kwargs):
        sensor = get_object_or_404(Sensor, pk=kwargs['pk'])
        predio = sensor.predio

        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area
        
        contexto = {
            'sensor':sensor,
            'predio':predio, 
            'consumo_mes':consumo_mes, 
            'consumo_pessoa':consumo_pessoa, 
            'consumo_area':consumo_area,            
            }
        return render(request, 'swenergy/editar.html', contexto)
    def post(self,request,*args,**kwargs):
        sensor = get_object_or_404(Sensor, pk=request.POST['id'])
        sensor.titulo = request.POST['titulo']
        sensor.save()

        predio = sensor.predio

        consumo_mes = 0
        for sensor in predio.sensor_set.all():
            for consumo in sensor.consumo_set.all():
                if consumo.total:
                    consumo_mes =consumo_mes + float(consumo.total)
        
        consumo_pessoa = consumo_mes/predio.populacao
        consumo_area = consumo_mes/predio.area

        consumos_diarios = Consumo.objects.filter(tipo='diario').filter(sensor=sensor)
        consumos_mensais = Consumo.objects.filter(tipo='mensal').filter(sensor=sensor)

swenergy/templates/swenergy/base.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        {% block head %}
        <meta charset="UTF-8">
        <title>SW - Energy</title>
        {% endblock %}
        {% block scripts %}
        {% endblock %}

        {% block links %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        {% block style %}       
        {% endblock %}
        {% block main-menu %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand"href=" {% url 'swenergy:index' %}">SWEnergy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active" title="Início">
                  <a class="nav-link" href=" {% url 'swenergy:indexPredio' predio.id %}">Edifício: </a>                  
                </li>
                <li class="nav-item active" title="Detalhes">
                  <a class="nav-link" href="{% url 'swenergy:detalhesPredio' predio.id %}"> {{predio.nome}} 
                    <span class="sr-only">(current)</span></a>
                </li>
    
                <li class="nav-item">
                    <a class="nav-link">Meta(Kwh): {{predio.meta}} </a>
                </li>

                <li class="nav-item" >
                    <span class="nav-link"> Consumo(kwh): {{consumo_mes}}</span>
                </li>                

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Relatórios
                  </a>                  
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">                    
                    <a class="dropdown-item" href="http://127.0.0.1:8000/relatoriopdf/" download="Relatorio.pdf">Baixar relatório</a> - 
                    <a class="dropdown-item" href="{% url 'swenergy:relatoriopdf' predio.id%}"> Ver relátorio geral</a>
                  </div>
                </li>
                
                <li  class="nav-item">
                  <form method=”GET”>
                    <div class=”input-group-prepend”>     
                      <select  name="filtro" style="margin: 10px 3px;">
                        <option type="text" name="mes" id="mes" value="1">Janeiro</option>
                        <option type="text" name="mes" id="mes" value="2">Fevereiro</option>
                        <option type="text" name="mes" id="mes" value="3">Março</option>
                        <option type="text" name="mes" id="mes" value="4">Abril</option>
                        <option type="text" name="mes" id="mes" value="5">Maio</option>
                        <option type="text" name="mes" id="mes" value="6">Junho</option>
                        <option type="text" name="mes" id="mes" value="7">Julho</option>
                        <option type="text" name="mes" id="mes" value="8">Agosto</option>
                        <option type="text" name="mes" id="mes" value="9">Setembro</option>
                        <option type="text" name="mes" id="mes" value="10">Outubro</option>
                        <option type="text" name="mes" id="mes" value="11">Novembro</option>
                        <option type="text" name="mes" id="mes" value="12">Dezembro</option>
                      </select>
                      <button class="btn btn-outline-dark" style="margin: 4px 0px; padding: 3px 5px;" type=”submit” id="button-addon1">filtrar</button>
                    </div>
                  </form>                                      
                </li>                                           

              </ul>
            </div>
            <ul>
            {% if user.is_authenticated %}
                <li class="d-flex justify-content-between align-items-center" style="margin-left: 200px;">
                  <a class="btn btn-outline-dark" href="{% url 'logout' %}?next=/">Logout</a>
                </li>
                {% else %}
                <li class="d-flex justify-content-between align-items-center">                  
                  <a class="btn btn-outline-dark" href="{% url 'login'%}">Login</a>
                </li>
                <li class="d-flex justify-content-between align-items-center">
                  <a class="btn btn-outline-dark" href="{% url 'swenergy:cadastro' %}">Cadastre-se</a>
                </li>
           
                {% endif %}                

              </ul>
          </nav>

        {% endblock %}
 
        {% block msg %}

            {% if msg %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <div class="alert alert-primary" role="alert">
                {{msg}}
              </div> 
              <span aria-hidden="true">&times;</span>
            </button>
                       
            {% endif %}

            {% if msg_sucess %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <div class="alert alert-success" role="alert">
                {{msg_sucess}}
              </div>            
              <span aria-hidden="true">&times;</span>
            </button>
            
            {% endif %}
            
            {% if msg_erro %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <div class="alert alert-danger" role="alert">
                {{msg_erro}}
              </div>                            
              <span aria-hidden="true">&times;</span>
            </button>            
            {% endif %}
        
        {% endblock %}
        
        

        {% block conteudo %}
        {% endblock %}
    </body>
</html>

swenergy/templates/swenergy/detalhesPredio.html
{% extends "swenergy/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <title>Detalhes do Edifício</title>
    <meta charset="UTF-8">
    {% endblock %}
</head>
<body>
    
    {% block conteudo %}
    
    <section style="padding: 5% 2%;">
        <div class="card w-75" style="padding: 2%">
            <div class="card-body">
              <h2 class="card-title">{{predio.nome}}</h2>
              <hr>
                <div class="d-flex" style="padding: 5%;">
                    
                    <div>
                        <h5 class="card-title">Dados gerais</h5>
                        <p class="card-text" >
                            <span>Meta: {{predio.meta}}             </span><br>
                            <span>População: {{predio.populacao}}   </span><br>
                            <span>Pavimentos: {{predio.pavimentos}} </span><br>
                            <span>Pot. Inst.: {{predio.PotInst}}    </span><br>
                            <span>Geração F.V.: {{predio.geracaoFV}}</span><br>
                            <span>Idade: {{predio.idade}}           </span><br>
                            <span>Trafifa Energética: {{predio.tarifaFP}}</span><br>
                        </p>
                    </div>
                    

                    <div style="margin-left:10%;">
                        <h5 class="card-title">Nível de eficiência-RTQ-C</h5><br>
                        <ul>
                            <li class="d-flex justify-content-between align-items-center">Sistema <span class="badge badge-primary ">Nota</span></li>
                            <li class="d-flex justify-content-between align-items-center">Iluminação
                            {% if predio.Iluminacao == "A" %}
                            <span class="badge badge-success ">{{predio.Iluminacao}}</span></li>
                            {% elif predio.Iluminacao == "B" %}
                            <span class="badge badge-warning ">{{predio.Iluminacao}}</span></li>
                            {% else %}
                            <span class="badge badge-danger ">{{predio.Iluminacao}}</span></li>
                            {% endif %}

                            <li class="d-flex justify-content-between align-items-center">Condicion. de ar 
                            {% if predio.CondAr == "A" %}
                            <span class="badge badge-success ">{{predio.CondAr}}</span></li>
                            {% elif predio.CondAr == "B" %}
                            <span class="badge badge-warning ">{{predio.CondAr}}</span></li>
                            {% else %}
                            <span class="badge badge-danger ">{{predio.CondAr}}</span></li>
                            {% endif %}         

                            <li class="d-flex justify-content-between align-items-center">Envoltória
                            {% if predio.envoltoria == "A" %}
                            <span class="badge badge-success ">{{predio.envoltoria}}</span></li>
                            {% elif predio.envoltoria == "B" %}
                            <span class="badge badge-warning ">{{predio.envoltoria}}</span></li>
                            {% else %}
                            <span class="badge badge-danger ">{{predio.envoltoria}}</span></li>
                            {% endif %}
                            </li>
                        </ul>
                    </div>

              </div>
              <a href="{% url 'swenergy:editarPredio' predio.id %}" class="btn btn-primary" style="margin-left: 5%;">Editar Dados</a>
              <a href="{% url 'swenergy:eficiencia' predio.id %}" class="btn btn-primary" style="margin-left: 10%;">Editar Notas</a>
            </div>
          </div>
        
        <fieldset style="margin-top: 30px;">
            
            <h3>Sensores:</h3>                 
            
            <div style="margin: 20px;">
                {% for sensor in predio.sensor_set.all %}
                <div class="d-flex">
                    <h4><a href="{% url 'swenergy:detalhes' sensor.id%}">{{sensor}}</a></h4>                    
                </div>
                
                {% endfor %}
                <hr>
            </div>    
              
        </fieldset>
    </section>  
    {% endblock %}
    
</body>
</html>

swenergy/templates/swenergy/index.html
{% extends "swenergy/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  {% block head %}
    <meta charset="UTF-8">
    <title>SW - Energy</title>
    <!--<meta http-equiv="refresh" content="5; {% url 'swenergy:index' %}">-->
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href= {% static "swenergy/css/style.css" %}>
    <link rel="preload" href= {% static "swenergy/js/script.js" %} as="script" />
  {% endblock %}

</head>
{% block main-menu %}
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    SWEnergy
  </a>
  <ul>
    {% if user.is_authenticated %}
    <li style="margin-left: 34px;"><a class="btn btn-outline-dark" href="{% url 'logout' %}?next=/">Logout</a></li>
    {% else %}
    <li><a class="btn btn-outline-dark"  href="{% url 'login'%}">Login</a></li>
    <li><a class="btn btn-outline-dark" href="{% url 'swenergy:cadastro' %}">Cadastre-se</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

{% block conteudo %}
<body>
    <script type="text/javascript" src="https://jscharting.com/JSC15/JSCharting.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

  <section class="corpo" >

    <ul class="list-group" style="padding-left: 25%; width: 50%; margin: 10% 10%;">
      <li class="list-group-item d-flex justify-content-between align-items-center" style="text-align: center;">
        Edifícios: <a class="btn btn-light" href="{% url 'swenergy:addPredio'%}" style="font-size: 80%;">Novo Edifício</a>
      </li>
      {% for predio in predios %} 
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'swenergy:indexPredio' predio.id %}">{{predio.nome}} - ID: {{predio.id}}</a>
        <a class="badge badge-primary badge-pill" href=" {% url 'swenergy:detalhesPredio' predio.id %}">
            Detalhes
        </a>
      </li>
      {% endfor %}
    </ul>
  </section>
</body>    
{% endblock %}
</html>